### ISSUE TITLE
How do I launch using visual studio 2022?

### ISSUE THREAD

**Issue by Turokirill** [ai-zen/live2d-copilot#1]
![image](https://github.com/ai-zen/live2d-copilot/assets/89459445/00fe8c0c-56f0-4cde-84b7-b20fbcea7130)
After executing all the commands, I do not understand which file should be run. The program asks you to select a file to run.

**Comment by Turokirill** [comment]
When trying to run through the terminal "node main/scripts/build.mjs", it gives an error: 

[build.mjs] clear dist dir
[build.mjs] copy public files
[build.mjs] build 'main' and 'payload'
[build.mjs] build started ./src/preload.ts
[build.mjs] build started ./src/main.ts
X X [[ERRORERROR]]  Could not resolve "./src/preload.ts"Could not resolve "./src/main.ts"



[build.mjs] build ended ./src/preload.ts
[build.mjs] build ended ./src/main.ts
C:\Users\TUROK\Desktop\live2d-copilot-main\node_modules\.pnpm\esbuild@0.19.4\node_modules\esbuild\lib\main.js:1650
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
error: Could not resolve "./src/preload.ts"
    at failureErrorWithLog (C:\Users\TUROK\Desktop\live2d-copilot-main\node_modules\.pnpm\esbuild@0.19.4\node_modules\esbuild\lib\main.js:1650:15)
    at C:\Users\TUROK\Desktop\live2d-copilot-main\node_modules\.pnpm\esbuild@0.19.4\node_modules\esbuild\lib\main.js:1059:25
    at C:\Users\TUROK\Desktop\live2d-copilot-main\node_modules\.pnpm\esbuild@0.19.4\node_modules\esbuild\lib\main.js:1526:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

**Comment by Turokirill** [comment]
I started it using vs code, now the error is "process.version.modules 116
(node:1564) UnhandledPromiseRejectionWarning: Error: failed to init the steamworks API". As I understand it, you need to specify your steam api key, but why?

**Comment by LZQCN** [comment]
- This project has not been released, so many developers cannot run it directly.
- This project will be released on Steam after completion.
- This project relies on some features in Steam, especially the Workshop.

For developers who are not whitelisted, you can try manually changing the APPID from `2570090` to `480` in `packages/main/src/modules/steamworksManager.ts`.
Alternatively, you can comment out `this._client = steamworks.init(this.APP_ID);`.
This will allow the project to run normally.

In addition, in the latest version (as of 2024/01/16), it is possible to launch this project without starting Steam. During the launch process, you will receive a warning but it will not cause startup failure or freezing.
